
name: daily updater

on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ruby:2.6.4
    steps:
      - uses: actions/checkout@v1
      - name: data update
        run: |
          git config user.name "daily_updater"
          git config user.email ${{ secrets.EMAIL }}
          git remote set-url origin https://asaba-zauberer:${{ secrets.PASS }}@github.com/asaba-zauberer/covid19-akita
          cd tool/ruby
          gem install bundler --no-document
          bundle config set deployment 'true'
          bundle install --jobs 4 --retry 3
          bundle exec rake
          cd ../../
          git add .
          git commit -m "daily update" || echo "No changes to commit"
          git push origin development
